import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#111315",
  },
  content: {
    padding: 16,
    gap: 16,
  },
  loadingWrap: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  loadingText: {
    color: "#f3f4f6",
    fontSize: 18,
    fontWeight: "600",
  },
  hero: {
    backgroundColor: "#1b1f24",
    borderRadius: 24,
    padding: 20,
    gap: 8,
  },
  installBanner: {
    backgroundColor: "#1b1f24",
    borderRadius: 18,
    padding: 14,
    borderWidth: 1,
    borderColor: "#2b3138",
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  installBannerTextWrap: {
    flex: 1,
    gap: 4,
  },
  installBannerTitle: {
    color: "#f3f4f6",
    fontSize: 15,
    fontWeight: "800",
  },
  installBannerText: {
    color: "#cbd5e1",
    fontSize: 13,
    lineHeight: 18,
  },
  installBannerButton: {
    backgroundColor: "#f59e0b",
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  installBannerButtonText: {
    color: "#111315",
    fontWeight: "800",
  },
  installBannerClose: {
    paddingHorizontal: 8,
    paddingVertical: 8,
  },
  installBannerCloseText: {
    color: "#94a3b8",
    fontWeight: "700",
  },
  eyebrow: {
    color: "#f59e0b",
    fontSize: 13,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  card: {
    backgroundColor: "#1a1d21",
    borderRadius: 20,
    padding: 16,
    gap: 14,
    borderWidth: 1,
    borderColor: "#2b3138",
  },
  sectionTitle: {
    color: "#f3f4f6",
    fontSize: 20,
    fontWeight: "800",
  },
  addRow: {
    flexDirection: "row",
    gap: 10,
  },
  input: {
    flex: 1,
    backgroundColor: "#0f1216",
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: "#374151",
    color: "#f3f4f6",
    fontSize: 15,
  },
  primaryButton: {
    backgroundColor: "#d97706",
    borderRadius: 14,
    minWidth: 48,
    alignItems: "center",
    justifyContent: "center",
  },
  primaryButtonText: {
    color: "#111315",
    fontWeight: "800",
    fontSize: 22,
    lineHeight: 22,
  },
  secondaryButton: {
    alignSelf: "flex-start",
    backgroundColor: "#f59e0b",
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  secondaryButtonText: {
    color: "#111315",
    fontWeight: "800",
  },
  emptyText: {
    color: "#94a3b8",
    fontSize: 15,
  },
  heroActions: {
    flexDirection: "row",
    gap: 10,
    marginTop: 6,
  },
  personCard: {
    gap: 14,
    paddingBottom: 14,
    borderBottomWidth: 1,
    borderBottomColor: "#2b3138",
  },
  personHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 12,
  },
  personName: {
    color: "#f3f4f6",
    fontSize: 17,
    fontWeight: "800",
  },
  personMeta: {
    color: "#94a3b8",
    fontSize: 13,
    marginTop: 2,
  },
  headerActions: {
    alignItems: "flex-end",
    gap: 8,
  },
  removeText: {
    color: "#f87171",
    fontWeight: "700",
  },
  metricsWrap: {
    gap: 10,
  },
  moneyField: {
    gap: 6,
  },
  quickActions: {
    gap: 8,
    paddingTop: 4,
  },
  quickActionsLabel: {
    color: "#d1d5db",
    fontSize: 13,
    fontWeight: "700",
  },
  quickButtonsRow: {
    flexDirection: "row",
    gap: 8,
  },
  quickButton: {
    flex: 1,
    backgroundColor: "#252b33",
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: "#374151",
    alignItems: "center",
  },
  quickButtonText: {
    color: "#f8fafc",
    fontSize: 13,
    fontWeight: "800",
  },
  moneyLabel: {
    color: "#d1d5db",
    fontSize: 13,
    fontWeight: "700",
  },
  moneyInput: {
    backgroundColor: "#0f1216",
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: "#374151",
    color: "#f3f4f6",
    fontSize: 15,
  },
  summaryGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  summaryBox: {
    flexGrow: 1,
    flexBasis: "47%",
    backgroundColor: "#15191d",
    borderRadius: 16,
    padding: 14,
    borderWidth: 1,
    borderColor: "#2b3138",
    minHeight: 90,
    justifyContent: "space-between",
  },
  summaryLabel: {
    color: "#94a3b8",
    fontSize: 13,
    fontWeight: "700",
  },
  summaryValue: {
    color: "#f3f4f6",
    fontSize: 20,
    fontWeight: "800",
  },
  balanceRow: {
    gap: 4,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#2b3138",
  },
  balanceHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 12,
  },
  balanceShare: {
    color: "#fbbf24",
    fontWeight: "800",
  },
  balanceMeta: {
    color: "#94a3b8",
    fontSize: 13,
  },
  balanceStatus: {
    fontSize: 15,
    fontWeight: "800",
  },
  positiveText: {
    color: "#4ade80",
  },
  negativeText: {
    color: "#f87171",
  },
  neutralText: {
    color: "#cbd5e1",
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.75)",
    alignItems: "center",
    justifyContent: "center",
    padding: 20,
  },
  modalCard: {
    width: "100%",
    maxWidth: 360,
    backgroundColor: "#1a1d21",
    borderRadius: 24,
    padding: 20,
    borderWidth: 1,
    borderColor: "#2b3138",
    gap: 14,
  },
  modalTitle: {
    color: "#f9fafb",
    fontSize: 22,
    fontWeight: "800",
  },
  modalText: {
    color: "#cbd5e1",
    fontSize: 14,
    lineHeight: 20,
  },
  qrWrap: {
    backgroundColor: "#ffffff",
    borderRadius: 20,
    padding: 16,
    alignItems: "center",
    alignSelf: "center",
  },
  primaryWideButton: {
    backgroundColor: "#d97706",
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  scannerScreen: {
    flex: 1,
    backgroundColor: "#111315",
    padding: 16,
    gap: 16,
  },
  scannerHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
  },
  scannerFrame: {
    flex: 1,
    minHeight: 360,
    borderRadius: 24,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#2b3138",
  },
  camera: {
    flex: 1,
  },
});
